#!/bin/sh
echo "hellosvn post-commit before" >>/tmp/svn.log
SVN = /usr/bin/svn
WEB = /var/www/html/blog/
export LANG=en_US.UTF-8
/usr/bin/svn update --username zhou --password 123456t /var/www/html/blog/
>>/tmp/svn.log
chown -R root:root /var/www/html/blog
#$SVN update $WEB –-username zho –-password 123456t 
#svn update /var/www/html/emarket/ –username zhou –password 123456t –non-interactive
#!/bin/shREPOS=”$1″REV=”$2″export LANG=zh_CN.UTF-8svn up /media/data/wwwroot/meeting 
# $SVN update $WEB --username zhou --password 123456t 
# POST-COMMIT HOOK
# The post-commit hook is invoked after a commit.  Subversion runs
# this hook by invoking a program (script, executable, binary, etc.)
# named 'post-commit' (for which this file is a template) with the 
# following ordered arguments:
#
#   [1] REPOS-PATH   (the path to this repository)
#   [2] REV          (the number of the revision just committed)
#
# The default working directory for the invocation is undefined, so
# the program should set one explicitly if it cares.
#
# Because the commit has already completed and cannot be undone,
# the exit code of the hook program is ignored.  The hook program
# can use the 'svnlook' utility to help it examine the
# newly-committed tree.
#
# On a Unix system, the normal procedure is to have 'post-commit'
# invoke other programs to do the real work, though it may do the
# work itself too.
#
# Note that 'post-commit' must be executable by the user(s) who will
# invoke it (typically the user httpd runs as), and that user must
# have filesystem-level permission to access the repository.
#
# On a Windows system, you should name the hook program
# 'post-commit.bat' or 'post-commit.exe',
# but the basic idea is the same.
# 
# The hook program typically does not inherit the environment of
# its parent process.  For example, a common problem is for the
# PATH environment variable to not be set to its usual value, so
# that subprograms fail to launch unless invoked via absolute path.
# If you're having unexpected problems with a hook program, the
# culprit may be unusual (or missing) environment variables.
# 
# Here is an example hook script, for a Unix /bin/sh interpreter.
# For more examples and pre-written hooks, see those in
# the Subversion repository at
# http://svn.apache.org/repos/asf/subversion/trunk/tools/hook-scripts/ and
# http://svn.apache.org/repos/asf/subversion/trunk/contrib/hook-scripts/


REPOS="$1"
REV="$2"
# mailer.py commit "$REPOS" "$REV" /path/to/mailer.conf
